# https://hub.docker.com/r/library/tomcat/tags/
FROM tomcat:8.5.35-jre8
MAINTAINER "wuweixiang <wuweixiang.alex@gmail.com>"
#EXPOSE 80 8080 443

#CMD ["/usr/local/tomcat/catalina.sh","run"] && tail -f /usr/local/tomcat/logs/catalina.out